- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ radarr_packages }}"
    state: present

- name: Establish Directories
  block:
    - name: "{{ radarr_root }}"
      ansible.builtin.file:
        path: "{{ radarr_root }}"
        state: directory
        owner: radarr
        group: media
        mode: "02775"

    - name: Radarr Subdirectories
      ansible.builtin.file:
        path: "{{ radarr_root }}/{{ item }}"
        state: directory
        owner: radarr
        group: media
        mode: "02775"
      loop:
        - app
        - data
        - logs
        - versions

- name: Pull Updated Version
  block:
    - name: Download Radarr Release
      ansible.builtin.get_url:
        url: "{{ radarr_github_url }}/v{{ radarr_version }}/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz"
        mode: "0775"
        checksum: "{{ radarr_sha256 }}"
        dest: "{{ radarr_root }}/versions/radarr_{{ radarr_version }}.tar.gz"
        owner: ansible
        group: media

    - name: Create Release Archive Folder
      ansible.builtin.file:
        path: "{{ radarr_root }}/versions/radarr_{{ radarr_version }}"
        state: directory
        owner: radarr
        group: media
        mode: "02775"

    - name: Decompress Release
      ansible.builtin.unarchive:
        owner: ansible
        group: media
        src: "{{ radarr_root }}/versions/radarr_{{ radarr_version }}.tar.gz"
        dest: "{{ radarr_root }}/versions/radarr_{{ radarr_version }}"

- name: Radarr Service
  block:
    - name: Service File
      ansible.builtin.template:
        backup: true
        src: /tank/appdata/ansible/roles/radarr/templates/radarr_service
        dest: "{{ radarr_service }}"
        owner: root
        group: media
        mode: "0664"
      register: updated_service
      notify: Start App
