- name: Install Common Packages
  ansible.builtin.package:
    name: "{{ radarr_packages }}"
    state: present

- name: Establish Directories
  block:
    - name: "{{ radarr_root }}"
      ansible.builtin.file:
        path: "{{ radarr_root }}"
        state: directory
        owner: "{{ radarr_user }}"
        group: "{{ radarr_group }}"
        mode: "02775"

    - name: Radarr Subdirectories
      ansible.builtin.file:
        path: "{{ radarr_root }}/{{ item }}"
        state: directory
        owner: "{{ radarr_user }}"
        group: "{{ radarr_group }}"
        mode: "02775"
      loop:
        - app
        - data
        - logs
        - versions

    # - name: "{{ radarr_root }}/data"
    #   ansible.builtin.file:
    #     path: "{{ radarr_root }}/data"
    #     state: directory
    #     owner: "{{ radarr_user }}"
    #     group: "{{ radarr_group }}"
    #     mode: "02775"

    # - name: "{{ radarr_root }}/logs"
    #   ansible.builtin.file:
    #     path: "{{ radarr_root }}/logs"
    #     state: directory
    #     owner: "{{ radarr_user }}"
    #     group: "{{ radarr_group }}"
    #     mode: "02775"

    # - name: "{{ radarr_root }}/versions"
    #   ansible.builtin.file:
    #     path: "{{ radarr_root }}/versions"
    #     state: directory
    #     owner: "{{ radarr_user }}"
    #     group: "{{ radarr_group }}"
    #     mode: "02775"

- name: Pull Updated Version
  ansible.builtin.get_url:
    url: "{{ radarr_download_url }}"
    mode: "0775"
    checksum: "{{ radarr_sha256 }}"
    dest: "{{ radarr_root }}/versions/radarr_{{ radarr_version }}.tar.gz"
    owner: ansible
    group: "{{ radarr_group }}"
