# App and Ownership
media_app_name:
media_app_service_acct: arrservice
media_app_owner: "{{ media_app_name }}"
media_app_group: media

# Release
media_app_version:
media_app_download_url:
media_app_github_url:
media_app_sha256:
media_app_release:

# Folders
media_app_root: "{{ appdata }}/{{ media_app_name }}"
media_app_versions: "{{ media_app_root }}/versions"
media_app_app_dir: "{{ media_app_root }}/app"
media_app_data_dir: "{{ media_app_root }}/data"
media_app_library:
media_app_dirs:
media_app_root_dir: /tank/media
media_app_app_srv:
media_app_sys_srv:
media_app_bind_ro:
media_app_bind_rw:

# Service and Dependencies
media_app_service_file: "/etc/systemd/system/{{ media_app_name }}.service"
media_app_service_name: "{{ media_app_name }}.service"
media_app_service_wants: []
media_app_service_after: []
media_app_packages: []
media_app_service_exec:
