- name: Pull Updated Version
  block:
    - name: Download Release
      ansible.builtin.get_url:
        url: "{{ media_app_download_url }}"
        mode: "0644"
        checksum: "{{ media_app_sha256 }}"
        dest: "{{ media_app_root }}/versions/{{ media_app_name }}_{{ media_app_version }}.tar.gz"
        owner: "{{ media_app_owner }}"
        group: "{{ media_app_group }}"

    - name: Create Release Archive Folder
      ansible.builtin.file:
        path: "{{ media_app_root }}/versions/{{ media_app_name }}_{{ media_app_version }}"
        state: directory
        owner: "{{ media_app_owner }}"
        group: "{{ media_app_group }}"
        mode: "02775"

    - name: Decompress Release
      ansible.builtin.unarchive:
        owner: "{{ media_app_owner }}"
        group: "{{ media_app_group }}"
        src: "{{ media_app_root }}/versions/{{ media_app_name }}_{{ media_app_version }}.tar.gz"
        dest: "{{ media_app_root }}/versions/{{ media_app_name }}_{{ media_app_version }}"
