- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags: [media_app, packages]

- name: Users
  ansible.builtin.import_tasks: users.yml
  tags: [media_app, users]

- name: Directories
  ansible.builtin.import_tasks: dirs.yml
  tags: [media_app, dirs]

- name: Download
  ansible.builtin.import_tasks: download.yml
  tags: [media_app, download]

- name: Service
  ansible.builtin.import_tasks: service.yml
  tags: [media_app, service]

- name: Link Release
  ansible.builtin.import_tasks: link.yml
  tags: [media_app, link]
