- name: Setup Service
  block:
    - name: Service File
      ansible.builtin.template:
        backup: true
        src: "{{ appdata }}/ansible/roles/media_app/templates/app_service.j2"
        dest: "{{ media_app_service_file }}.test"
        owner: root
        group: "{{ media_app_group }}"
        mode: "0664"
      register: updated_service
      notify: Restart App
