- name: Restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
