- name: Install python3-virtualenv - "{{ media_app_exec_name }}"
  ansible.builtin.package:
    name: python3-virtualenv
    state: present

- name: Create Virtual Environment - "{{ media_app_exec_name }}"
  ansible.builtin.pip:
    virtualenv: "{{ media_app_python_venv }}"
    requirements: "{{ media_app_app }}/requirements.txt"
    state: present

- name: Set Virtual Environment Ownership - "{{ media_app_exec_name }}"
  ansible.builtin.file:
    path: "{{ media_app_python_venv }}"
    state: directory
    owner: "{{ media_app_owner }}"
    group: "{{ media_app_group }}"
    recurse: true
