- name: Maintenance
  hosts: control
  become: true
  gather_facts: true

  tasks:
    - name: Refresh APT cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag
      changed_when: false

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Maintenance-triggered reboot"
        reboot_timeout: 900
      when: reboot_flag.stat.exists

    - name: Install maintenance service
      ansible.builtin.copy:
        dest: /etc/systemd/system/ansible-maint.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Ansible maintenance
          After=network-online.target
          Wants=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/flock -n /run/ansible-maint.lock /usr/bin/ansible-playbook /tank/appdata/ansible/playbooks/maintenance.yml -l localhost
      notify: Reload systemd

    - name: Install maintenance timer
      ansible.builtin.copy:
        dest: /etc/systemd/system/ansible-maint.timer
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Run Ansible maintenance weekly

          [Timer]
          OnCalendar=Sun *-*-* 03:00:00
          RandomizedDelaySec=900
          Persistent=true

          [Install]
          WantedBy=timers.target
      notify:
        - Reload systemd
        - Enable and start timer

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Enable and start timer
      ansible.builtin.systemd:
        name: ansible-maint.timer
        enabled: true
        state: started
